[phases.setup]
# Forzamos la instalación de git y git-lfs en el sistema operativo del contenedor
nixPkgs = ["python311", "git", "git-lfs"]

[phases.install]
# Ejecutamos el pull aquí, donde Git sí está disponible durante el build
cmds = [
    "git lfs install",
    "git lfs pull",
    "pip install -r requirements.txt"
]

[start]
# Quitamos los comandos de git del inicio para evitar el error de "command not found"
cmd = "streamlit run app-mejorada-debug.py --server.port $PORT --server.address 0.0.0.0"